server:
  port: 443
#  ssl:
#    key-store:
#    key-store-password:
template:
  templates:
    - {"templateId":"1","templateFilePath":"F:/project/kafka/kafka-study/src/main/resources/template/template.json","active":true}
    - {"templateId":"2","templateFilePath":"F:/project/kafka/kafka-study/src/main/resources/template/template.json","active":false}
  template-result-type: 0  #/0-文件获取 1-数据库获取 2-ES获取
  template-result-file-path: "F:/project/kafka/kafka-study/src/main/resources/template/templateResult.json"


wechat:
  kafka:
    bootstrap_servers_config: "192.168.213.161:9092"
    acks_config: "all"
    retries_config: "0"
    batch_size_config: "16384"
    linger_ms_config: "1"
    buffer_memory_config: "33554432"
    key_serializer_class_config: "org.apache.kafka.common.serialization.StringSerializer"
    value_serializer_class_config: "org.apache.kafka.common.serialization.StringSerializer"
    partitioner_class_config: "com.tj.jiangzh.kafka.producer.PartitionSample"
